
[tools]
deno = "2.5.1"
golang = "1.20"
node = "22.16.0"
lua = "latest"
python = "3.11"
pipx = 'latest'
bun = "latest"
ruby = "latest"
rust = "latest"
zig = "latest"
usage = "latest"

[settings]
experimental = false
idiomatic_version_file_enable_tools = []
