services:
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    user: "0:0"
    ports:
      - "5008:8000"
    environment:
      - DEFAULT_THEME=${DEFAULT_THEME:-dark}
      - DEFAULT_THEME_COLOR=${DEFAULT_THEME_COLOR:-blue}
      - SECRET_KEY=${SECRET_KEY:-some_long_random_secret}
      # the domain where you want to access PdfDing, e.g. pdfding.com
      - HOST_NAME=${HOST_NAME:-127.0.0.1}
      # In production set the following values to True
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-FALSE}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-FALSE}
    volumes:
      - /home/square/data/share/pdfding/sqlite_data:/home/nonroot/pdfding/db
      - /home/square/data/share/pdfding/media:/home/nonroot/pdfding/media
    restart: unless-stopped
